version: '3.8'

services:

  api:
    build:
      context: ./Api
    ports:
      - "5000:80"
    depends_on:
      - worker

  worker:
    build:
      context: ./Worker
    volumes:
      - data:/app

volumes:
  data: